create table usuario(
ID int not null AUTO_INCREMENT,
nombreUsuario varchar(20) not null unique,
pass varchar(40) not null,
tipo bit not null default 0,
email varchar(35) not null unique,
nombreCompleto varchar(70) not null,
nivelEducativo varchar(25) not null,
especializacion varchar(50) not null,
habilitado bit default 1,
PRIMARY KEY(ID)
);


insert into usuario(nombreUsuario, pass, email, nombreCompleto, nivelEducativo, especializacion) values
('enrT', 'usuario', 'enrique.torres1999@yahoo.com','Enrique Torrez', 'Licenciatura', 'Ciencias computacionales'),
('jasonR', 'usuario', 'jason.rodriguez@gmail.com','Jason Rodriguez', 'Maestria', 'Ciencias computacionales'),
('pedroF', 'usuario', 'pedro.flores@hotmail.com', 'Pedro Flores', 'Bachillerato', 'Ciencias computacionales'),
('ang95', 'usuario', 'angel.hernandez@outlook.com','Angel Hernandez', 'Licenciatura', 'Ciencias computacionales'),
('metalMario', 'usuario', 'mario.febacher@gmail.com', 'Mario fabacher', 'Licenciatura', 'Ciencias computacionales'),
('mariaS', 'usuario', 'maria.scott@gmail.com', 'Maria Scott', 'Licenciatura', 'Ciencias computacionales'),
('peterO', 'usuario', 'peter.owen@gmail.com', 'Peter Owen', 'Licenciatura', 'Ciencias computacionales'),
('stevieN', 'usuario', 'stevie.wonder@gmail.com', 'Stevie Wonder', 'Licenciatura', 'Ciencias computacionales'),
('jenD', 'usuario', 'jenny.grosso@gmail.com', 'Jennifer Del Grosso', 'Bachillerato', 'Ciencias computacionales'),
('ET1990', 'usuario', 'erik.taylor@gmail.com', 'Erik Taylor', 'Licenciatura', 'Ciencias computacionales'),
('PROF1', 'pass11', 'profesor1@gmail.com', 'Jonathan Scott', 'Maestria', 'Ciencias computacionales'),
('PROF2', 'pass11', 'profesor2@gmail.com', 'Jessica Reeves', 'Maestria', 'Ciencias computacionales'),
('PROF3', 'pass11', 'profesor3@gmail.com', 'Eduardo Robles', 'Maestria', 'Ciencias computacionales');

create table curso(
ID int not null AUTO_INCREMENT,
id_profesor int not null,
nombre varchar(70) not null,
fechaCreacion datetime not null default NOW(),
fechaModificacion datetime not null default NOW(),
descripcion varchar(255),
esProgresivo bit not null default 0,
habilitado bit not null default 1,
precio decimal(6, 2) not null default 0.0,
codigoPrivado varchar(50),
PRIMARY KEY(ID),

FOREIGN KEY(id_profesor)
references usuario(ID)
on delete cascade
);

insert into curso(id_profesor, nombre) values
(11, "Programacion en C++ desde cero"),
(12, "Introduccion a la intelegencia artificial"),
(13, "Programacion y Diseño Web"),
(11, "Programacion en Java desde cero"),
(11, "Programacion en C# desde cero"),
(11, "Programacion en PHP desde cero"),
(12, "Diseño y programacion de compiladores"),
(13, "Programacion en Python"),
(12, "Programacion en Python"),
(11, "Programacion en JavaScript desde cero");


create table transmision(
ID int not null AUTO_INCREMENT,
id_curso int not null,
nombre varchar(70) not null,
fechaAgendada datetime not null,
estatus tinyint not null default 0,
ubicacion text not null,
PRIMARY KEY(ID),

FOREIGN KEY(id_curso)
references curso(ID)
on delete cascade
);


insert into transmision(id_curso, nombre, fechaAgendada, estatus, ubicacion) values
(1, "Introduccion a las clases y objetos", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/ABRP_5RYhqU"),
(2, "Creacion de una red neuronal simple en python", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/kft1AJ9WVDk"),
(3, "Creacion de una interfaz de inicio de sesion en HTML y CSS", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/OWNxUVnY3pg"),
(4, "Creacion de hilos al extender la clase Thread", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/0ySznjdXMEA"),
(7, "Introduccion a los analizadores lexicos y gramaticas", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/WccZQSERfCM"),
(1, "Clases abstractas y metodos virtuales puros", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/ndz3EHpFEZc"),
(7, "Gramaticas ambiguas y como eliminar la ambiguedad", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/9vmhcBpZDcE"),
(2, "Algoritmos utilizados en Machine Learning", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/I7NrVwm3apg"),
(8, "Clases y objetos", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/VYXdpjCZojA"),
(9, "Que son las variables", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/Z1Yd7upQsXY"),
(10, "Creando un juego con programacion funcional", "2019-03-21 11:00:00", 1, "https://www.youtube.com/embed/bRlvGoWz6Ig");


create table usuario_curso(
id_usuario int not null,
id_curso int not null,
rating tinyint,
foreign key(id_usuario) references usuario(ID) on delete cascade,
foreign key(id_curso) references curso(ID) on delete cascade,
unique(id_usuario, id_curso)
);

insert into usuario_curso(id_usuario, id_curso) values
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(1, 7),
(1, 8),
(1, 9),
(1, 10),
(2, 1),
(2, 2),
(2, 3),
(2, 4),
(2, 5),
(2, 6),
(2, 7),
(2, 8),
(2, 9),
(2, 10),
(3, 1),
(3, 2),
(3, 3),
(3, 4),
(3, 5),
(3, 6),
(3, 7),
(3, 8),
(3, 9),
(3, 10),
(4, 1),
(4, 2),
(4, 3),
(4, 4),
(4, 5),
(4, 6),
(4, 7),
(4, 8),
(4, 9),
(4, 10),
(5, 1),
(5, 2),
(5, 3),
(5, 4),
(5, 5),
(5, 6),
(5, 7),
(5, 8),
(5, 9),
(5, 10),
(6, 1),
(6, 2),
(6, 3),
(6, 4),
(6, 5),
(6, 6),
(6, 7),
(6, 8),
(6, 9),
(6, 10),
(7, 1),
(7, 2),
(7, 3),
(7, 4),
(7, 5),
(7, 6),
(7, 7),
(7, 8),
(7, 9),
(7, 10),
(8, 1),
(8, 2),
(8, 3),
(8, 4),
(8, 5),
(8, 6),
(8, 7),
(8, 8),
(8, 9),
(8, 10),
(9, 1),
(9, 2),
(9, 3),
(9, 4),
(9, 5),
(9, 6),
(9, 7),
(9, 8),
(9, 9),
(9, 10),
(10, 1),
(10, 2),
(10, 3),
(10, 4),
(10, 5),
(10, 6),
(10, 7),
(10, 8),
(10, 9),
(10, 10);